## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1) Seu código aqui
dfmaterias = pd.DataFrame() #cria um dataframe com todas as materias e alunos 
dfmaterias['Mat'] = df_mat
dfmaterias['Por'] = df_por
dfmaterias['Geo'] = df_geo
dfmaterias['Ing'] = df_ing
dfmaterias['His'] = df_his
dfmaterias['Fis'] = df_fis 
dfmaterias['Qui'] = df_qui
dfmaterias # exibe o dataframe

    Mat  Por  Geo  Ing  His  Fis  Qui
0     6    7    7    3    1    8    3
1    19   10    0    0    0   11    8
2    14   16    0    5    7    4    4
3    10    7    3    4    0    0    8
4     7    2    2    7    0    9    3
..  ...  ...  ...  ...  ...  ...  ...
95    6    4    7    1    4    9    3
96    8    1    4    6    1    4    3
97   23    5    0    2    4    1    5
98    0   10    3    1    5   10   11
99   11   15    0    1    6    7    2

[100 rows x 7 columns]

In [3]:
# Nao tinha compreendido se a questao era pra calcular o percentual de "CADA" aluno por materia,
# ou se era o percetual de todos os alunos por materia.
# Sendo assim fiz a proporcao de acerto de todos os alunos juntos por materia.
# Criei 3 novas colunas a uma matriz transposta para representar cada materia por linha.

df = dfmaterias.T #cria o dataframe transposto das materias
df['media'] = df.mean(axis =1) #calcula a media dos alunos por materia
df['total'] = ['24','18','8','8','8','12','12'] # cria a coluna total
fn = lambda valor: int(valor) # funçao que converte os valores de 'object' para 'int'
df['total'] = df['total'].apply(fn) # aplica a funçao na coluna total
df['prop_acerto'] = (df['media']/df['total']) #calcula a proporçao de acerto dos alunos por materia
df #exibe o dataframe com as colunas geradas

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,media,total,prop_acerto
Mat,6,19,14,10,7,20,6,18,22,10,...,12,0,6,8,23,0,11,11.85,24,0.493750
Por,7,10,16,7,2,2,0,4,9,6,...,16,5,4,1,5,10,15,7.23,18,0.401667
Geo,7,0,0,3,2,5,7,4,2,3,...,5,2,7,4,0,3,0,3.36,8,0.420000
Ing,3,0,5,4,7,3,7,7,7,6,...,5,6,1,6,2,1,1,3.81,8,0.476250
His,1,0,7,0,0,2,5,7,6,4,...,6,1,4,1,4,5,6,3.60,8,0.450000
Fis,8,11,4,0,9,9,0,1,5,8,...,6,3,9,4,1,10,7,5.32,12,0.443333
Qui,3,8,4,8,3,9,4,8,7,2,...,6,8,3,3,5,11,2,5.43,12,0.452500

In [4]:
df['prop_acerto'] #exibe apenas a proporçao de acerto por materia

Mat    0.493750
Por    0.401667
Geo    0.420000
Ing    0.476250
His    0.450000
Fis    0.443333
Qui    0.452500
Name: prop_acerto, dtype: float64

In [5]:
# 2) Seu código aqui

dfmaterias['Soma'] = dfmaterias.sum(axis = 1) #cria uma coluna chamada soma com a soma dos acertos de todas as materias
dfmaterias['Soma']

0     35
1     48
2     50
3     32
4     30
      ..
95    34
96    27
97    40
98    40
99    42
Name: Soma, Length: 100, dtype: int64

In [6]:
# 3) Seu código aqui
dfmaterias['porcent_geral'] = dfmaterias['Soma']/90 # gera o percentual de acerto de cada aluno em relaçao ao total de questoes
dfmaterias['porcent_geral']

0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
        ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667
Name: porcent_geral, Length: 100, dtype: float64

In [7]:
# 4) Seu código aqui
# Correçao realiazada. Antes a analise foi feita sobre o numero de acertos e nao sobre a porcentagem geral.

dfmaterias['porcent_geral'] = dfmaterias['porcent_geral'] * 100

In [8]:
df_aprovados = dfmaterias[dfmaterias['porcent_geral']>= 45]
len(df_aprovados)

47

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [9]:
# seu código aqui

df_eliminados = dfmaterias[(df_mat['Qt_acertos'] == 0) | #criterio para eliminaçao
                      (df_fis['Qt_acertos'] == 0) |
                      (df_qui['Qt_acertos'] == 0)]

df_eliminados #exibe apenas os alunos eliminados pelo criterio acima

    Mat  Por  Geo  Ing  His  Fis  Qui  Soma  porcent_geral
3    10    7    3    4    0    0    8    32      35.555556
6     6    0    7    7    5    0    4    29      32.222222
10   10    8    3    2    1    7    0    31      34.444444
12   20    8    3    7    1    0    3    42      46.666667
14    7   11    1    7    1    4    0    31      34.444444
20   23   11    6    5    6    2    0    53      58.888889
25    0    4    7    4    0    4    8    27      30.000000
26   11   14    6    2    7    0    0    40      44.444444
27   21   13    1    5    7    3    0    50      55.555556
33   14    8    0    5    6    6    0    39      43.333333
35   11   14    6    3    3    0   11    48      53.333333
49    8    1    1    0    1    0    8    19      21.111111
56    7    6    7    5    6    0    8    39      43.333333
65    1    8    2    4    3    0    6    24      26.666667
66    5    4    3    6    3    0   10    31      34.444444
72   11   16    3    4    7    0    9    50      55.555556
73    1   16    2    4    3    0   11    37      41.111111
74    9   11    0    7    5    7    0    39      43.333333
84   15    1    0    5    1    0    4    26      28.888889
89   23   11    7    7    6    9    0    63      70.000000
92   14   10    1    6    1    8    0    40      44.444444
94    0    5    2    6    1    3    8    25      27.777778
98    0   10    3    1    5   10   11    40      44.444444

In [10]:
#contagem de alunos eliminados por esse criterio
eliminados,_ = df_eliminados.shape
print(eliminados, 'foram eliminados pelo criterio de zerar matematica ou fisica ou quimica')

23 foram eliminados pelo criterio de zerar matematica ou fisica ou quimica

In [11]:
# Media dos alunos eliminados em historia e Geografia
media_his = dfmaterias['His'].mean() #calcula a media dos alunos eliminados em historia
media_geo = dfmaterias['Geo'].mean() #calcula a media dos alunos eliminados em Geografica

print('A media dos alunos em historia foi de', media_his,'e em geografia foi de',media_geo,'!')

A media dos alunos em historia foi de 3.6 e em geografia foi de 3.36 !

In [12]:
# subtraindo dos qualificados por nao zerar, os que tiveram a nota inferior a 45.
df_aprovados_new = df_aprovados[(df_aprovados['Mat']!=0) &
                                (df_aprovados['Qui']!=0) &
                                (df_aprovados['Fis']!=0)]

In [13]:
#quantidade de aprovados que tiraram 45 ou mais e nao zeraram matematica ou fisica ou quimica
len(df_aprovados_new)

41

In [14]:
#DataFrame completo dos alunos aprovados ate o momento
df_aprovados_new

    Mat  Por  Geo  Ing  His  Fis  Qui  Soma  porcent_geral
1    19   10    0    0    0   11    8    48      53.333333
2    14   16    0    5    7    4    4    50      55.555556
5    20    2    5    3    2    9    9    50      55.555556
7    18    4    4    7    7    1    8    49      54.444444
8    22    9    2    7    6    5    7    58      64.444444
11   23    6    2    0    6    4    2    43      47.777778
17   21   15    2    2    4    2    6    52      57.777778
18   20    4    3    5    3   11    4    50      55.555556
24   20    2    7    5    3   11    2    50      55.555556
29   16    0    0    2    7   11    8    44      48.888889
31   15   13    3    1    3    9   10    54      60.000000
34   18   14    1    0    6    3    3    45      50.000000
36   22    9    6    6    1    4    8    56      62.222222
37   19   12    5    7    1    6    2    52      57.777778
39    4   16    2    4    6    9    8    49      54.444444
40   18    3    6    3    6    5    6    47      52.222222
42   20    6    7    7    2    3    3    48      53.333333
44    6   14    7    3    1    3    9    43      47.777778
45   17   10    0    2    6    9    4    48      53.333333
48   17    6    0    7    5    9   11    55      61.111111
50   20    9    0    3    1    7    3    43      47.777778
51    1   12    7    3    5    4   10    42      46.666667
52   19    5    5    5    0    3    4    41      45.555556
53   14   11    3    4    3    7    3    45      50.000000
55   11   10    4    4    5    1    6    41      45.555556
60   16    8    0    4    4    7    9    48      53.333333
62   17    6    2    4    7    1    9    46      51.111111
67   21    0    7    2    4    2   10    46      51.111111
68    9    9    5    3    6   10    1    43      47.777778
70   21   14    0    3    5   11    8    62      68.888889
71   17    8    7    6    4    2    9    53      58.888889
75    3    6    7    6    6    9    5    42      46.666667
77   15    2    5    7    6   11    7    53      58.888889
78   14   16    7    2    7   11    9    66      73.333333
80   13   16    5    1    7    2    1    45      50.000000
81   22   16    2    0    4    1   10    55      61.111111
82    7   16    7    1    1    2    9    43      47.777778
83   20    1    5    6    3    6    1    42      46.666667
88   20    1    1    5    7    9    7    50      55.555556
93   12   16    5    5    6    6    6    56      62.222222
99   11   15    0    1    6    7    2    42      46.666667

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [15]:
#foi feito o upload do arquivo no Kaggle
arquivo = '/kaggle/input/registros-de-vacinao-do-acre/reg_vac_ACRE.csv'

In [16]:
# 1) Sua solução aqui

df = pd.read_csv(arquivo,sep =';')

vacinas,_ = df.shape # para computar a quantidade de vacinas vou usar o .shape
print('A quantidade de vacinas registradas na base é de ',vacinas,'.')

A quantidade de vacinas registradas na base é de  169071 .

In [17]:
# 2)
df['paciente_id'].nunique() # Verifica somente a quantidade de id unicos

120517

In [18]:
# 3)
df.head(5)

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [19]:
# separando o valor unico da primeira dose na variavel
# para realizar a contagem dos valores unicos dentro do registro
primeira_dose = df['vacina_descricao_dose'].unique()[0]
df['paciente_id'].loc[df['vacina_descricao_dose'] == primeira_dose].nunique()

119713

In [20]:
# 3) solução alternativa
df_primeira_dose = df[df['vacina_descricao_dose'] == primeira_dose]
df_primeira_dose['paciente_id'].nunique()

119713

In [21]:
# 4)
df_menores_18 = df[df['paciente_idade']<18]
df_menores_18['paciente_id'].nunique()

47

In [22]:
# 5)
df.columns.unique() # Analisando qual coluna será utilizada para diferencias os estabelecimentos unicos

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [23]:
# Utilizando o nome fantasia para abrangir todos os estabelecimentos que aplicaram as vacinas
# independente de possuiem a mesma razao social. Assim será contados matrizes e filiais.
df['estalecimento_nofantasia'].nunique()

103

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vacinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [24]:
# 1) Usando a funçao .copy
df_menores_18_copy = df[df['paciente_idade']<18].copy()

In [25]:
# 2) exibe as colunas do DataFrame
df_menores_18_copy.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [26]:
# 3) Realizar a contagem do campo 'vacina_categoria_nome'

df_menores_18_copy['vacina_categoria_nome'].value_counts()

vacina_categoria_nome
Povos Indígenas                     33
Trabalhadores de Saúde               9
Povos e Comunidades Tradicionais     9
Comorbidades                         2
Faixa Etária                         1
Name: count, dtype: int64

In [27]:
# 4) lista com informaçoes dos estabelecimentos

lista_estabelecimentos = ['estabelecimento_valor','estabelecimento_razaosocial','estalecimento_nofantasia',
                         'estabelecimento_municipio_codigo','estabelecimento_municipio_nome',
                         'estabelecimento_uf']

In [28]:
# 5) selecionar apenas essas variaveis com o metodo.loc

df_list_estabelecimentos = df_menores_18_copy.loc[:,lista_estabelecimentos]
df_list_estabelecimentos.head(2)

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC

In [29]:
#6) aplicar o .drop_duplicates na lista

df_list_estabelecimentos = df_list_estabelecimentos.drop_duplicates()
df_list_estabelecimentos.shape

(18, 6)

In [30]:
# mostra todos os estabelecimentos unicos no formato de lista
# usando o campo de razao social um estabelecimento possui 'filiais' com outro nome fantasia.
# por isso foi utilizado o nome fantasia para contemplar todos os 18 estabelecimentos.
df_list_estabelecimentos['estalecimento_nofantasia'].value_counts()

estalecimento_nofantasia
ESF JOAO ALVES DA SILVA                                        1
DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AMBIENTAL          1
UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE                1
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS                1
HOSPITAL REGIONAL DO JURUA                                     1
POLO BASE DE MANCIO LIMA                                       1
POLO BASE INDIGENA                                             1
POLO INDIGENA DE MANOEL URBANO                                 1
UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAUACA POLO BASE    1
POLO BASE DE ASSIS BRASIL                                      1
POLO BASE DE CRUZEIRO DO SUL                                   1
UBS VICENTE VARELA DE ALMEIDA                                  1
POLO BASE DE PORTO WALTER                                      1
POLO BASE DE FEIJO                                             1
POLO BASE DE MARECHAL THAUMATURGO                              1
CENTRO DE SAUDE DIAMANTINO MACEDO                              1
SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL               1
SAUDE DA FAMILIA RIBEIRINHA                                    1
Name: count, dtype: int64